### ISSUE TITLE
Add retry logic

### ISSUE THREAD

**Issue by jcampbell05** [Autoenhance-ai/autoenhance-python#9]
Eventually it would be great if we could add some retry logic to the send_request method to help guard against temporary network issue

https://github.com/Autoenhance-ai/autoenhance-python/blob/3407583d8b93bd953b5ca49017fc0652be296af1/auto_enhance/auto_enhance.py#L8

**Comment by aoulaa** [comment]
what error codes might server return ? 
i can do some logic based on it

**Comment by aoulaa** [comment]
or retry logic can be based on whats ?

**Comment by jcampbell05** [comment]
So for the `send_request` method if there is an underlying network error i.e `could not connect` or any error code other than unauthorised or bad request then we should re-try incase it is a temporary issue which may be resolved.
